### ISSUE TITLE
invoke issue: Tasks must have an initial Context argument!

### ISSUE THREAD

**Issue by dongfengdejia** [dongfengdejia/RIDE#1]
I try use inv for execute some command, there report error:

Traceback (most recent call last):
  File "C:\Python27\Scripts\inv-script.py", line 11, in <module>
    load_entry_point('invoke==0.22.1', 'console_scripts', 'inv')()
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\program.py"
, line 282, in run
    self.parse_collection()
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\program.py"
, line 356, in parse_collection
    self.load_collection()
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\program.py"
, line 508, in load_collection
    module, parent = loader.load(coll_name)
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\loader.py",
 line 69, in load
    module = imp.load_module(name, fd, path, desc)
  File "E:\github\RIDE_My\tasks.py", line 63, in <module>
    @task
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\tasks.py",
line 290, in task
    return Task(args[0], **kwargs)
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\tasks.py",
line 63, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\tasks.py",
line 153, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "C:\Python27\lib\site-packages\invoke-0.22.1-py2.7.egg\invoke\tasks.py",
line 148, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!

**Comment by dongfengdejia** [comment]
check the invoke github: https://github.com/pyinvoke/invoke/issues/362
the issue should be fixed, but why there still reproduce at my environment?

**Comment by dongfengdejia** [comment]
issue fixed by add the "ctx" for all task function
