### ISSUE TITLE
add CI process for keep the code quality

### ISSUE THREAD

**Issue by dongfengdejia** [dongfengdejia/RIDE#3]

**Comment by dongfengdejia** [comment]
CI add: https://travis-ci.org/dongfengdejia/RIDE

**Comment by dongfengdejia** [comment]
Meet some problem for wxPython 2.8 build, so keep the issue exist, and not add the CI process.

**Comment by dongfengdejia** [comment]
find the last solution for fix we meet issues:
    sudo apt-get install python-wxgtk2.8 for install the wxPython2.8
    virtualenv:
       system_site_packages: true

**Comment by dongfengdejia** [comment]
BTW, there still have two case failed (they are pass at local):
======================================================================
FAIL: test_library_from_resourcefile_variable (namespace.test_namespace.TestKeywordSuggestions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dongfengdejia/RIDE/utest/namespace/test_namespace.py", line 174, in test_library_from_resourcefile_variable
    self._assert_import_kws(sugs, 'Dialogs')
  File "/home/travis/build/dongfengdejia/RIDE/utest/namespace/test_namespace.py", line 321, in _assert_import_kws
    assert_true(len(sugs) > 0)
AssertionError: False is not true
======================================================================
FAIL: test_suggestions_for_datafile (namespace.test_namespace.TestKeywordSuggestions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dongfengdejia/RIDE/utest/namespace/test_namespace.py", line 299, in test_suggestions_for_datafile
    self._assert_import_kws(sugs, 'Dialogs')
  File "/home/travis/build/dongfengdejia/RIDE/utest/namespace/test_namespace.py", line 321, in _assert_import_kws
    assert_true(len(sugs) > 0)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 995 tests in 9.059s
FAILED (failures=2)
